version: "3"
services:
    api:
        image: nehhy/fastapi
        ports:
            - 8000:8000
        env_file:
            - ./docker.env
        # volumes:
        #     - ./:/usr/src/app:ro
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=fastapi=${POSTGRES_DB}

        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: